### ISSUE TITLE
Channels is an array of arrays...

### ISSUE THREAD

**Issue by jomag** [sciyoshi/redmine-slack#108]
Today I tried to use Redmine-Slack on a new Redmine setup and at first failed to get it to send notifications to Slack. It seems that the channel list is an array of arrays. Here's the params variable used to build the json payload:

    {
      :text=>"...", :link_names=>1, :username=>"Redmine", 
      :attachments=>[{:text=>"Test test test test test test.", :fields=>[]}],
      :icon_url=>"https://raw.github.com/sciyoshi/redmine-slack/gh-pages/icon.png",
      :channel=>["#general"]
    }

If I hardcode the channel to "#general" it works as expected.

I think this is related to this commit 7575feca8716acf52c669af7725db6054e897ed3.

**Comment by sciyoshi** [comment]
@jomag that commit is also supposed to loop over each channel (https://github.com/sciyoshi/redmine-slack/commit/7575feca8716acf52c669af7725db6054e897ed3#diff-940c9450f10c5d3e2f04b2590a6ec411R152) - can you paste the traceback where you see this being sent?

**Comment by sciyoshi** [comment]
I've reverted the commit that caused this - hopefully you shouldn't see this issue anymore.

**Comment by rnaud** [comment]
Ah yes, I missed the channels_for_project proj.parent. That's an upper recursive call. So it will respond with an array of array. Will fix.
