### ISSUE TITLE
Notification for @user_name, if he mentioned in comments

### ISSUE THREAD

**Issue by developerswebb** [sciyoshi/redmine-slack#111]
https://confluence.jetbrains.com/display/YTD65/Slack+Integration#SlackIntegration-CreateaSlackAccountfortheJabberBot
With youtrack we can use @user_name for push-notify in slack. Can we do the same in Redmine?

**Comment by rafael-queo** [comment]
I would like that too

**Comment by sciyoshi** [comment]
@developerswebb @rafael-h-ferreira - can you try the PR in issue #124 and see if this helps your use case?
