### ISSUE TITLE
no configuration page

### ISSUE THREAD

**Issue by retroj** [sciyoshi/redmine-slack#118]
Hello,

I installed redmine-slack in a redmine 3.0 installation.  It is listed in the Plugins administration page, but clicking 'Configure' leads to an error message from redmine:

404

The page you were trying to access doesn't exist or has been removed.

What could be wrong?  Thank you.

**Comment by sioaji** [comment]
Hello,

Me neither. But I fixed it by issue #24 .
I was wrong plugin's folder name. "redmine-slack".
I fixed to "redmine_slack". (underscore)
And then retry migrate and restart Redmine.

I would be happy if this information is helpful for you.

**Comment by retroj** [comment]
Okay, sounds like I probably have the redmine_slack directory in the wrong location?  This is on a Debian system, and the plugin path is /usr/share/redmine/lib/plugins/.  There are many other plugins in that same directory.

**Comment by retroj** [comment]
I created /usr/share/redmine/plugins and put redmine_slack into that directory, and the issue was resolved.
