### ISSUE TITLE
newly created issues are not sent to slack.

### ISSUE THREAD

**Issue by jensolsson** [sciyoshi/redmine-slack#119]
I have an e-mail handler set up using redmine/htdocs/extra/mail_handler/rdm-mailhandler.rb

Problem is that only updates are posted to slack. If an incoming mail creates an issue it will not be posted to slack. Can this be fixed?

**Comment by jensolsson** [comment]
Realized that this is a duplicate to #80 hopefully it can be merged and released?

**Comment by sciyoshi** [comment]
Thanks @jensolsson - #80 has been merged, can you check if this fixes your issue?

**Comment by jensolsson** [comment]
Works perfectly! Thanks!
--
Jens Olsson
