### ISSUE TITLE
Not work Redmine 4.0.0

### ISSUE THREAD

**Issue by u2fuji** [sciyoshi/redmine-slack#146]
When I introduced Redmine 4.0 and introduced the plugin, it did not work with the latest commitment.

Error log
    Message from application: undefined method `to_prepare' for ActionDispatch::Callbacks:Class (NoMethodError)

The cause is "ActionDispatch :: Callbacks.to_prepare" of 5bf4d6906bbb348cf0feb543e847b9efe8b86650 .
Rails 5.1 removed ActionDispatch::Callbacks#to_prepare (see rails/rails@3f2b7d6); 

I returned one commit and made it running, it was operational.

Environment:
  Redmine version                4.0.0.stable.17794
  Ruby version                   2.4.5-p335 (2018-10-18) [x86_64-linux-gnu]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.7
  Git                            2.14.5
  Filesystem                     
Redmine plugins:
  redmine_mermaid_macro          1.0.0
  redmine_slack                  0.2

**Comment by bladekp** [comment]
`ActionDispatch::Callbacks.to_prepare` was removed
[here from rails](https://github.com/rails/rails/commit/3f2b7d60a52ffb2ad2d4fcf889c06b631db1946b), `ActiveSupport::Reloader.to_prepare` should be used instead. *deprecate to_prepare: "use ActiveSupport::Reloader.to_prepare instead"*

**Comment by u2fuji** [comment]
I hope that #144 will be merged.
