### ISSUE TITLE
Broken link to redmine issue

### ISSUE THREAD

**Issue by AndrewUmansky** [sciyoshi/redmine-slack#19]
hello. There are a liittle bag in last version.
 Broken link to redmine issue. Please check screensht from slack
  http://screencast.com/t/rf1yAoYTcQ3w
< link > causes that link doesn work in slach
thx for great plugin

**Comment by sciyoshi** [comment]
@AndrewUmansky this seems more like a bug in Slack, and when I'm trying to reproduce this it seems to work correctly. Closing, but if you continue to see this behavior, please reopen the issue. Thanks!
