### ISSUE TITLE
Configure link doesn't work in Redmine 

### ISSUE THREAD

**Issue by ShopfansJosh** [sciyoshi/redmine-slack#20]
Slack plugin appears in redmine, but when I click "configure" I am taken to this url: mysite.com/redmine/settings/plugins/redmine_slack

And I see an error message as follows:

https://www.dropbox.com/s/3ik8asq0tuyiu3h/Screenshot%202014-09-04%2014.18.01.png?dl=0

Any suggestions?

**Comment by smithmf** [comment]
@agronholm are you still having this issue? It sounds familiar to #24. Does that solution work for you?

**Comment by foozmeat** [comment]
I'm seeing a 404 form the configure link as well. I followed the above instructions. The log shows

```
Missing template, responding with 404
```

**Comment by foozmeat** [comment]
To solve this problem you need to rename the plugin folder to redmine_slack. I'll submit a PR for the README.

**Comment by foozmeat** [comment]
My mistake. The README clearly states that you have to clone using the correct name. In my case I add my plugins as submodules so I didn't c/p the line from the README.

**Comment by sciyoshi** [comment]
Thanks @foozmeat - maybe there's a better way to indicate this or detect the error. Closing this issue in the meantime.
