### ISSUE TITLE
Undefined method `delete' for nil:NilClass

### ISSUE THREAD

**Issue by CharlieBeckett** [sciyoshi/redmine-slack#23]
Hi,
Looking forward to using this plugin but I'm getting a undefined method 'delete' for nil:NilClass when updating/creating an issue.

I'm on a somewhat dated platform..is that the problem ?
Environment:
  Redmine version                2.3.2.stable
  Ruby version                   1.9.3-p385 (2013-02-06) [i386-mingw32]
  Rails version                  3.2.13

Help most appreciated

Cheers
Charlie

**Comment by CharlieBeckett** [comment]
Hi,
I've narrowed it down and I think I'm now stuck at a different issue.  

The url_for_project and channel_for_project were throwing errors.  I've tweaked the code to just return nil forcing the plugin to read from the global settings rather than project ones.  

However, I think the problem now maybe a proxy related problem as slack is blank.

**Comment by CharlieBeckett** [comment]
It's working.  I needed to create "Slack URL" and "Slack Channel" project custom fields first.  
Posts to slack now.  Awesome.  

Thanks all,

**Comment by smithmf** [comment]
Awesome! No need for thanks, @CharlieBeckett , you did all the work ;). Glad to see it is working
