### ISSUE TITLE
404 error resolved with this solution, but unable to configure chat, not working

### ISSUE THREAD

**Issue by sharavanakrishna** [sciyoshi/redmine-slack#24]
404 error resolved with this solution, but unable to configure chat, not working

**Comment by anthony99fr** [comment]
Hello, i had the same problem.

I can't access the plugin conguration page after the installation and got a 404 page.

Here is my configuration:

Environment:
  Redmine version                2.6.0.devel
  Ruby version                   1.9.3-p551 (2014-11-13) [x86_64-linux]
  Rails version                  4.1.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.3.5
  redmine_slack                  0.1

**Comment by smithmf** [comment]
Can you tell me where the `redmine_slack` plugin files are located on your Redmine install? Are they in `plugins` or `vendor/plugins`?

**Comment by anthony99fr** [comment]
The redmine_slack files are located in the plugins directory:
redmine/plugins/redmine-slack

**Comment by smithmf** [comment]
Hm, can you post the relevant section from the `log/production.log` where the 404 is occurring so we can see the request?

**Comment by bengizmo** [comment]
I see @anthony99fr is using redmine 2.6, which is what I have and am getting a similar error when accessing the Slack plugin configuration page - [redmine url]/settings/plugin/redmine_slack
![image](https://cloud.githubusercontent.com/assets/3747733/5692699/ea7e3936-98bc-11e4-80c3-faf8b7fa04d2.png)

Here's the `production.log` error:
>Started GET "/settings/plugin/redmine_slack" for 70.x.x.x at 2015-01-10 18:27:42 +0000
>Processing by SettingsController#plugin as HTML
>  Parameters: {"id"=>"redmine_slack"}
>  Current user: xxxxx (id=x)
>  Rendered settings/plugin.html.erb within layouts/admin (31.4ms)
>Missing template, responding with 404
>  Rendered common/error.html.erb within layouts/base (0.1ms)
>Completed 404 Not Found in 249.5ms (Views: 178.1ms | ActiveRecord: 28.9ms)

Here's my configuration:
>Environment:
>  Redmine version                2.6.0.stable.13648
>  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
>  Rails version                  3.2.21
>  Environment                    production
>  Database adapter               Mysql2
>SCM:
>  Subversion                     1.8.8
>  Git                            1.9.1
>  Filesystem                     
>Redmine plugins:
>  clipboard_image_paste          1.9
>  extended_fields                0.2.3
>  extended_profile               1.2.1
>  redmine_checklists             3.0.2
>  redmine_dashboard              3.0.0.dev0
>  redmine_slack                  0.1
>  redmine_theme_changer          0.1.0
>  redmine_work_time              0.2.16
>  sidebar                        0.1.2

I saw mention of requiring custom fields for this plugin, but I thought that was only if I wanted specialized routing after the plugin was working. Correct me if I'm wrong.

**Comment by anthony99fr** [comment]
Hi, here is my production.log error:

Started GET "/settings/plugin/redmine_slack" for XXX.XXX.XXX.XXX at 2015-01-12 10:31:36 +0100
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_slack"}
  Current user: abouillis (id=1)
  Rendered settings/plugin.html.erb within layouts/admin (2.4ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.1ms)
Completed 404 Not Found in 34ms (Views: 23.9ms | ActiveRecord: 2.4ms)

**Comment by smithmf** [comment]
Hm, I'm running a similar setup, at least for the version of Redmine:
>Environment:
>  Redmine version                2.6.0.stable.13817
>  Ruby version                   1.8.7-p358 (2012-02-08) [x86_64-linux]
>  Rails version                  3.2.21
>  Environment                    production
>  Database adapter               MySQL`

A key difference here is @anthony99fr and @bengizmo are running ruby version 1.9.3. My production log has the slack config view being rendered:
>  Rendered plugins/redmine_slack/app/views/settings/_slack_settings.html.erb (0.4ms)
>  Rendered settings/plugin.html.erb within layouts/admin (3.5ms)
>  Rendered admin/_menu.html.erb (129.1ms)
>  Rendered layouts/base.html.erb (23.1ms)
>Completed 200 OK in 184.1ms (Views: 179.3ms | ActiveRecord: 0.8ms)

So is `plugins/redmine_slack/app/view/settings/_slack_settings.html.erb` present? Also, just to make sure have you both run `rake redmine:plugins:migrate RAILS_ENV=production` after installing the plugin?

**Comment by bengizmo** [comment]
I had run the rake command after installation and rebooted the server. I was able to find the `plugins/redmine_slack/app/view/settings/_slack_settings.html.erb` file, which contained the following:
```
<p>
        <label for="settings_slack_url">Slack URL</label>
        <input type="text" id="settings_slack_url" size=80 value="<%= settings['slack_url'] %>" name="settings[slack_url]" />
</p>

<p>
        <label for="settings_channel">Slack Channel</label>
        <input type="text" id="settings_channel" value="<%= settings['channel'] %>" name="settings[channel]" />
</p>

<p>
        The channel can be changed on a per-project basis by creating a
        <a href="/custom_fields/new?type=ProjectCustomField">project custom field</a> named "Slack Channel" (without quotes).
</p>

<p>
        <label for="settings_username">Slack Icon</label>
        <input type="text" id="settings_icon" value="<%= settings['icon'] %>" name="settings[icon]" />
</p>

<p>
        <label for="settings_username">Slack Username</label>
        <input type="text" id="settings_username" value="<%= settings['username'] %>" name="settings[username]" />
</p>
```

Something else to note - I've also got Puma setup with Nginx as a reverse proxy in front of my Apache instance. Do you think that would cause any issues?

**Comment by smithmf** [comment]
Can you confirm the location of the plugin folder (`<redmine_path>/plugins/redmine_slack`)?

Other instances of missing plugin templates seem to indicate that the problem was a plugin folder being named differently than what the plugin is registered as (in `redmine_slack/init.rb` it registers itself as `redmine_slack`, as Redmine renders plugins, it does it from memory so it assumes the plugin directory is named the same as it was registered).

Nothing else seems to be jumping out. If you aren't having issues with other plugins, then I can't think of why the reverse proxy would just affect the slack plugin.

**Comment by anthony99fr** [comment]
Ok, i solved the problem.

My plugin was <redmine_path>/plugins/redmine-slack. I renamed it in <redmine_path>/plugins/redmine_slack and restarted Puma.

The plugins seems to work correctly.

**Comment by smithmf** [comment]
Awesome

@bengizmo any luck on your end?

**Comment by bengizmo** [comment]
Yup, just made that same change - plugin works if folder is named `/plugins/redmine_slack`(mine was also `/plugins/redmine-slack`)

Thanks guys!

**Comment by sciyoshi** [comment]
Awesome - thanks @smithmf for helping debug this. The instructions say to clone into `redmine_slack`, but this should probably be made clearer to avoid this problem for others.
