### ISSUE TITLE
Problem with proxy configuration

### ISSUE THREAD

**Issue by matbott** [sciyoshi/redmine-slack#30]
in the company where I work and I have installed redmine a proxy authentication is used to surf the internet. I discovered that the problem in the slack plugin is that it fails to send the information via the proxy. search the internet and found that ruby ​​does not use proxy variables but requires use Net :: HTTP directly in the code. so there will see this suggestion to use the plugins? Thank you

**Comment by sciyoshi** [comment]
Hi @matbott - this plugin uses the `httpclient` library for doing the HTTP request to Slack. The library supports using an HTTP proxy by setting the `HTTP_PROXY` environment variable. Try running Redmine with that variable set and see if it works for you. Thanks!
