### ISSUE TITLE
Link in slack to localhost

### ISSUE THREAD

**Issue by cakl** [sciyoshi/redmine-slack#33]
![image](https://cloud.githubusercontent.com/assets/641066/6176869/6c48bba8-b302-11e4-82c0-8b99a873abf5.png)

Link routes to http://localhost:3000/issues/1

Why? Did I missed something at the installation or is this a bug?

**Comment by pipeaesac** [comment]
+1

**Comment by nixmore** [comment]
This is a Redmine config issue. Try this out: http://www.redmine.org/boards/2/topics/2436

**Comment by sciyoshi** [comment]
Like @nixmore, this is a config issue with your Redmine install. Please reopen if you still have issues! Thanks,
