### ISSUE TITLE
Not compatible with popular "redmine_helpdesk" plugin

### ISSUE THREAD

**Issue by nixmore** [sciyoshi/redmine-slack#34]
Hey, I just installed your plugin and it worked on the first try. Thanks so much for this. I don't have the ability to troubleshoot this problem, but I thought you might want to know about it.

We use Redmine Helpdesk plugin (https://github.com/jfqd/redmine_helpdesk) and one of it's features it that you can email helpdesk@mycompany.com and it will auto-create issues. Problem is, when the issue gets created, your Slack plugin does not notify my channel.

I am here to help in any way other than hands-on programming, just let me know what I can do. I can test, bridge the gap between you and the author of the Helpdesk plugin, etc.

**Comment by joshmn** [comment]
+1 

I can look into this though. I'm pretty sure (though I've never touched redmine internals) it's just a problem with cascading hooks.

**Comment by ba221400** [comment]
+1, we are also using RedmineCRM's helpdesk and seeing the same thing.

**Comment by Kukuruts** [comment]
I had the same issue. The problem is that the helpdesk plugin doesn't trigger any hook the redmine-slack plugin listens to. I had to hack the helpdesk plugin to fix this. I don't have the latest version of the helpdesk plugin, so the line number may differ. 

in plugins/redmine_contacts_helpdesk/app/models/helpdesk_mailer.rb after "issue.save!" in line 314 I added
      Redmine::Hook.call_hook(:controller_issues_new_after_save, { :params => [], :issue => issue})

This fixed the problem for me.

**Comment by sciyoshi** [comment]
@nixmore - sounds like @Kukuruts found the best solution to this issue, which is to change the helpdesk plugin to trigger the appropriate hooks. Could you file a ticket with them, referencing this one? I'll keep it open in the meantime. Thanks!

**Comment by nixmore** [comment]
Issue created! https://github.com/jfqd/redmine_helpdesk/issues/89

**Comment by ba221400** [comment]
@Kukuruts what version of the helpdesk plugin are you on? We are using 2.2.9-pro and the helpdesk_mailer.rb file has two "issue.save!" lines in it (for creating and updating an issue). Adding the hook to both did not work for us--I'm digging through the logs and have not found any errors indicating why so far. Thanks!
