### ISSUE TITLE
support for Redmine 3.x?

### ISSUE THREAD

**Issue by pohutukawa** [sciyoshi/redmine-slack#35]
Redmine 3.0.0 just came out, and it would be awesome if the Slack integration would also work for the new/current Redmine 3.x series. I'm already missing it ... :-/

I'm completely at a loss with Ruby and Ruby-on-Rails, so unfortunately I can't help here. :-(

**Comment by sciyoshi** [comment]
Thanks @pohutukawa - I'm also unfamiliar with Redmine 3.0.0, but I can't imagine it would be hard to make it compatible. Is there a specific error you're seeing?

**Comment by JBenPiel** [comment]
@sciyoshi the error I get with this plugin in redmine 3.0.1 (I didn't try in 3.0.0) is a 404. I'm not sure if that's what @pohutukawa is also experiencing. When I try to configure the plugin within redmine I get

```
The page you were trying to access doesn't exist or has been removed.
```

The redmine production.log also shows 

```
Missing template, responding with 404
```

Hopefully this helps you, I can dig further if necessary but am not certain what other relevant info you may need.

**Comment by megheaiulian** [comment]
I have tested this in Redmine 3.0.1. While there is no error it doesn't trigger a post to the configured slack channel.  Maybe some hooks are different in the 3.x series?

**Comment by megheaiulian** [comment]
It seems to work in Redmine 3.0.1. It needed a # in front of the channel name.

**Comment by pohutukawa** [comment]
Sounds good, I'll give that a try soon. Unfortunately, as I had to "move on" from the failure and sort out other extension issues, I can't recall or reproduce the error I've seen again. But I'll post some feedback once I got a chance to test 3.0.1 ...

**Comment by pohutukawa** [comment]
OK, I have just upgraded to 3.0.1, and I can confirm that everything is working now again.

PS: It *may* have been that the previously reported issue was also in conjunction with the `redmine-agile` extension that also was misbehaving until I have reported the problem and got it resolved.

Anyway, it works here with 3.0.1 :-)

**Comment by Slind14** [comment]
everything works fine for me, too. Why not close it?

**Comment by pohutukawa** [comment]
Indeed, sorry ... busy times ... slipped my mind. Closing it now.
