### ISSUE TITLE
Plugin doesn't send anything

### ISSUE THREAD

**Issue by gotroch** [sciyoshi/redmine-slack#37]
We've installed and configured redmine-slack but the plugin doesn't send anything. 
Incoming Web Hook is enabled. I've tried the curl code from Slack doc and it's working. 

Could you please help me? Any suggestions? Thanks.

Redmine 2.2.2.stable

**Comment by smithmf** [comment]
Hi @gotroch, have you seen any errors being thrown in the Redmine logs? Also, did you configure the Slack plugin in Redmine to post to the desired channel?

**Comment by gotroch** [comment]
Hi @smithmf, 
there is nothing about slack in Redmine log. Yes I configured the Slack plugin to post info general channel.

**Comment by smithmf** [comment]
Hi @gotroch,
Is the general channel specified as "general" or did you put a # in front, so "#general"?

**Comment by gotroch** [comment]
Hi @smithmf ,
without #.

**Comment by smithmf** [comment]
Can you try prepending a '#'? Looks like that is how we are configured and not having problems.

**Comment by gotroch** [comment]
Thank you very much for your help. It's working now. My mistake.
