### ISSUE TITLE
send only title

### ISSUE THREAD

**Issue by igroykt** [sciyoshi/redmine-slack#38]
What i need to comment so plugin send only title (and description)?
I don't want see status,proirity,etc in message.
Tried to comment in listener.rb:
<               #}, {
<               #       :title => I18n.t("field_priority"),
<               #       :value => escape(issue.priority.to_s),
<               #       :short => true
<               #}, {
<               #       :title => I18n.t("field_assigned_to"),
<               #       :value => escape(issue.assigned_to.to_s),
<               #       :short => true

<               #when "tracker"
<               #       tracker = Tracker.find(detail.value) rescue nil
<               #       value = escape tracker.to_s
<               #when "project"
<               #       project = Project.find(detail.value) rescue nil
<               #       value = escape project.to_s
<               #when "status"
<               #       status = IssueStatus.find(detail.value) rescue nil
<               #       value = escape status.to_s
<               #when "priority"
<               #       priority = IssuePriority.find(detail.value) rescue nil
<               #       value = escape priority.to_s
<               #when "category"
<               #       category = IssueCategory.find(detail.value) rescue nil
<               #       value = escape category.to_s
<               #when "assigned_to"
<               #       user = User.find(detail.value) rescue nil
<               #       value = escape user.to_s
<               #when "fixed_version"
<               #       version = Version.find(detail.value) rescue nil
<               #       value = escape version.to_s
<               #when "attachment"
<               #       attachment = Attachment.find(detail.prop_key) rescue nil
<               #       value = "<#{object_url attachment}|#{escape attachment.filename}>" if attachment
<               #when "parent"
<               #       issue = Issue.find(detail.value) rescue nil
<               #       value = "<#{object_url issue}|#{escape issue}>" if issue

but it still send:
redmineBOT [09:44] 
[project] name updated status #38190: [HSPG-20301] title. description.
status
priority

**Comment by sciyoshi** [comment]
@igroykt you can remove the `attachments` parameter in the `speak` method here: https://github.com/sciyoshi/redmine-slack/blob/master/lib/redmine_slack/listener.rb#L70. Alternatively, this could be made a configuration option in the plugin itself if you're interested in helping!
