### ISSUE TITLE
Make Slack API requests in a separate thread

### ISSUE THREAD

**Issue by kallam1** [sciyoshi/redmine-slack#39]
Hi,
Thanks for the plugin, which is really helpful. 
After the plugin integration, I noticed that the redmine is responding too slow while creating and updating the issue. Could you please help me on whether I need to tweak anything here to improve the performance? We have thousands of issue records in our database, would this be a problem here?
Our environment details are as below
Environment:
  Redmine version                          2.3.0.stable
  Ruby version                             1.8.7 (i686-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         MySQL

**Comment by sciyoshi** [comment]
Hi @kallam1 - thanks for the report. It may be possible that posting to slack (which is done in-request) is taking extra time. You can try the patch here: https://github.com/antoin-m/redmine-slack/commit/2d4a6fc5dd470aed02403d20bff6de059433792f

Please let me know if that solves the problem - I'll probably include this fix in master as well.

**Comment by kallam1** [comment]
Hi Sciyoshi, thanks for the response. I tried this patch but no progress.

Redmine is waiting for the Slack message to be posted to display the page. Once the issue is appeared on slack, redmine started to respond. I think we need to have multi threading here.

Could you please review this again.

**Comment by Slind14** [comment]
:+1:

**Comment by WatchSteveDrum** [comment]
:+1: The mail handler script has an async option, so maybe that could be a useful reference for anyone who might be tempted to work on this?....

_hoping..._

**Comment by sciyoshi** [comment]
This should now be fixed in latest master thanks to @oirad. @kallam1 @Slind14 can you please see if this is working for you now? Thanks!
