### ISSUE TITLE
update installation instructions

### ISSUE THREAD

**Issue by lioman** [sciyoshi/redmine-slack#43]
I needed to run

    rake redmine:plugins:migrate RAILS_ENV=production

on installation. Perhaps you should include this in the README

**Comment by sciyoshi** [comment]
@lioman this plugin shouldn't require any database migrations. Are you sure there wasn't another plugin that was installed?

**Comment by lioman** [comment]
I had scrum and slack integration installed. But Scrum was not updated recently. Perhaps it was a weird side effect. But I think you need to save the settings of this plugin in database. Are there no extra field needed in database.

**Comment by sciyoshi** [comment]
@lioman there are no extra fields in the DB because it uses the existing configuration tables. I'm closing this issue, but we are planning on adding extra documentation in the meantime. Thanks!
