### ISSUE TITLE
redmine fails to load because of missing httpclient even though httpclient is installed

### ISSUE THREAD

**Issue by narabalki** [sciyoshi/redmine-slack#46]
Hi, I have a redmine (bitnami) installation (redmine 2.4) - I went to my /opt/bitnami/apps/redmine/htdocs/plugin folder and did "bundle install", I also created a Gemfile and referenced httpclient (as given in one of your issues) and did bundle install.
When I list gem list, it shows me httpclient (2.6.0.1)

But, when I run redmine and try to access it, it gives an error (see below). And since my redmine itself doesn't run I have to remove the plugin so that the production is not affected. Let me know if I am doing something wrong.

App 6120 stdout:
App 6120 stdout:
[ 2015-06-10 13:13:37.8584 5387/7f6fb7d25700 Pool2/Implementation.cpp:287 ]: Could not spawn process for application /opt/bitnami/apps/redmine/htdocs/: An error occured while starting up the preloader.
  Error ID: fcff345e
  Error details saved to: /tmp/passenger-error.hnNhYl
  Message from application: No such file to load -- httpclient (LoadError)
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`block in require'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`require'
  /opt/bitnami/apps/redmine/htdocs/plugins/redmine_slack/lib/redmine_slack/listener.rb:1:in `<top (required)>'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`require'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in`load_dependency'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:360:in`require_or_load'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:317:in `depend_on'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:233:in`require_dependency'
  /opt/bitnami/apps/redmine/htdocs/plugins/redmine_slack/init.rb:3:in `<top (required)>'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`require'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in`load_dependency'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
  /opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:155:in`block in load'
  /opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `each'
  /opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in`load'
  /opt/bitnami/apps/redmine/htdocs/config/initializers/30-redmine.rb:21:in `<top (required)>'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in`load'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in`load_dependency'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/engine.rb:652:in`block in load_config_initializer'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/engine.rb:651:in`load_config_initializer'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in`each'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `block in <class:Engine>'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in`instance_exec'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
  /opt/bitnami/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in`block in run_initializers'
  /opt/bitnami/ruby/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
  /opt/bitnami/ruby/lib/ruby/2.0.0/tsort.rb:183:in`block (2 levels) in each_strongly_connected_component'
  /opt/bitnami/ruby/lib/ruby/2.0.0/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
  /opt/bitnami/ruby/lib/ruby/2.0.0/tsort.rb:219:in`each_strongly_connected_component_from'
  /opt/bitnami/ruby/lib/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'

**Comment by narabalki** [comment]
Btw, the version numbers of redmine, ruby etc are given below

Environment:
  Redmine version                3.0.0.stable
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.0
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Cvs                            1.12.13
  Git                            1.9.5
  Filesystem                     
Redmine plugins:
  no plugin installed

**Comment by narabalki** [comment]
any comments or responses?

**Comment by camille28** [comment]
I also have a bitnami installation but with redmine 3.0.3 and Rails 4.2.1 and I have the same problem.
Did you find a solution ?

**Comment by inventionlabs** [comment]
No, I gave up on this plugin. Instead I use IFTTT. I have configured it to send a message to slack on receiving an email from redmine.

**Comment by camille28** [comment]
Do you send notifications from each project to a different channel or to only one ?
If you send to different channels could you send me your recipe ?

**Comment by narabalki** [comment]
I  am yet to work that one out. I tried it once unsuccessfully as redmine has the project name in its subject line but it is not #tagged. I think IFTTT expects it to be hashtags on the subject line. Need to see how I can get redmine to create mails that way. I will share it here if I find a way out.

**Comment by sciyoshi** [comment]
@inventionlabs @narabalki did you run the `bundle install` command from the plugin directory? Also, try running the Redmine plugin migration just in case:

    rake redmine:plugins:migrate RAILS_ENV=production

**Comment by narabalki** [comment]
I did try the bundle install from plugin directory and also did the redmine migrate. Maybe its some problem in the bitnami version - you may want to try it out sometime when you can and see if you get the same problem.

Anyways, for @camille28, I was able to achieve the filtering of notifications to different slack channels based on project. I had to change mailer.rb as follows (add a # before the project name). restart the services.

-- :subject => "[#{issue.project.name} - #{issue.tracker.name} ##{issue.id}] (#{issue.status.name}) #{issue.subject}" 
++ :subject => "[##{issue.project.name} - #{issue.tracker.name} ##{issue.id}] (#{issue.status.name}) #{issue.subject}"

Created a IFTTT with a trigger of mail with subject containing #[projectname] to a new slack channel. Only catch is IFTTT #hashtag condition does not allow blank spaces in project name. In my case I had a number of projects had a similar prefix, followed by a blank space and then specific name. I had to change some project names in redmine to get this working.

**Comment by a-b** [comment]
I was able to fix this problem by running
`cd /opt/bitnami/apps/redmine/htdocs`
`sudo aptitude install libhttpclient-ruby`
`bundle install --no-deployment`
`sudo  /opt/bitnami/ctlscript.sh restart apache`

make sure to backup everything because this command will upgrade gems

**Comment by rubendepedro** [comment]
Ok, I had trouble too trying to install this plugin on a Bitnami stack. After many unsuccessful attempts, I figured out this solution:

```
$ cd /opt/bitnami/apps/redmine/htdocs/plugins/
$ unzip redmine_checklists-3_1_3-light.zip
$ bundle exec rake redmine:plugins NAME=redmine_checklists RAILS_ENV=production
$ sudo /opt/bitnami/ctlscript.sh restart
```

Hope it helps you.

```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.0.0-p647 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Cvs                            1.12.13
  Git                            2.6.1
  Filesystem                     
Redmine plugins:
  redmine_checklists             3.1.3
  redmine_slack                  0.1
```

**Comment by kenjitayama** [comment]
This is how I got it working.
The Gemfile in my Redmine root directory had this:
```
# Load plugins' Gemfiles
Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
  eval_gemfile file
end
```

So I ran `bundle install` the same way I did for installing Redmine.

```
bundle install --without development test --path vendor/bundle
```

Maybe the command line is different(especially --path), depending on the instructions you were following.

My environment:
```
Environment:
  Redmine version                3.2.0.stable.14992
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               PostgreSQL
```

**Comment by rustikella** [comment]
Redmine on a docker container, developing a plugin for redmine.
I executed   _gem install httpclient_   and I had in  Gemfile (redmine directory) :

_# Load plugins' Gemfiles
Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
  eval_gemfile file
end_

but it didn't work.  I solved  this way:
into Gemfile (redmine directory)
......
gem "httpclient"
.......................
