### ISSUE TITLE
Agile Plugin status change not sending notification

### ISSUE THREAD

**Issue by dokun1** [sciyoshi/redmine-slack#47]
Whenever I go into an actual issue ticket and update the status, the notification posts to our slack channel that the status has updated.

We are using Redmine's Agile plugin (http://www.redminecrm.com/projects/agile/pages/1) and the act of dragging and dropping a task from "New" to "In Progress" is essentially the same this as a status change. However, this does not send a notification to the slack channel.

We are using Redmine 3.0.0.

**Comment by sciyoshi** [comment]
@dokun1 it sounds like the Agile plugin isn't triggering the appropriate hooks. Unfortunately it doesn't seem that their plugin is open source so I can't submit a PR to them. Could you please open an issue with them instead about calling the appropriate hooks? Thanks!

**Comment by igor9silva** [comment]
I've tested other plugins as well, like `redmine_issue_dynamic_edit` and `redmine_helpdesk` and none of them seem to work well with Slack integration.

I'll be looking into a solution for that and update here as soon as I achieve one.
