### ISSUE TITLE
Send messages async

### ISSUE THREAD

**Issue by Slind14** [sciyoshi/redmine-slack#49]
Hey,

since I added redmine-slack all ticket creations and edits went super slow. Once I remove the plugin it is normal again. Would it be possible to implement it async. This also wouldn't break the service when slack is down/the connection to slack is failing.

**Comment by sciyoshi** [comment]
@Slind14 - thanks for the report. Totally open to doing this, just haven't had the bandwidth. This is also a duplicate of #39. PRs welcome!

**Comment by Slind14** [comment]
ahh I was looking for async, background.. but not additional thread :)
