### ISSUE TITLE
No slack posts being made

### ISSUE THREAD

**Issue by mossytrees** [sciyoshi/redmine-slack#53]
Slack webhook integration was tested outside of redmine using curl.  

Installed redmine-slack using instructions in README.  Plugin is configured, but no updates make it to slack.  How do I go about troubleshooting this?  I don't see any mention of the redmine_slack plugin in the redmine/log/production.log other than loading the configuration pages.

``` Environment:
  Redmine version                2.5.3.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_slack                  0.1
```

**Comment by sciyoshi** [comment]
@mummylegs do you see new issues get posted to slack? There is now a configuration option for posting updates that might be the problem.

**Comment by mummylegs** [comment]
New issues do not get posted to slack.  The "post updates" option is checked.  Besides just fixing this specific issue I'd love some information on how to actually troubleshoot this.  Where/how do I get logs, or see what's happening with the plugin?

I did run tcpdump while posting a comment to slack using curl and could see the traffic.  I see no such traffic when creating or updating issues in redmine.

**Comment by akanoop** [comment]
Same here. No new posts/updates.
```
Environment:
  Redmine version                3.0.4.stable
  Ruby version                   2.0.0-p645 (2015-04-13) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Mercurial                      2.1
  Cvs                            1.12.13
  Git                            1.9.5
  Filesystem                     
Redmine plugins:
  redmine_mail_handler_clean_body_regexp 0.1
  redmine_slack                  0.1
  scrum                          0.11.1
```

**Comment by Genosite** [comment]
Check your channel name. He must be started by '#'

**Comment by akanoop** [comment]
Thanks @Genosite .I should have tried that at the first place!

**Comment by mummylegs** [comment]
It should be noted that in theory you can omit the # if you are sending to a private group instead of a public channel -- test it out with curl using the instructions for your slack webhook and you will see that it works perfectly fine to omit the # if you have a private group with the name you specify.

However, in my case, I have tried it with the # and the name of a public channel in my slack team, and it still doesn't work.  As I said, in my case, I see no attempt at traffic to the slack servers when updating or creating an issue, and monitoring network activity with tcpdump.

**Comment by Genosite** [comment]
Do you install the dependency pluging ? (httpclient)

**Comment by mummylegs** [comment]
Sorry, missed that comment, yes, I ran bundle install as per the installation instructions and it installed the httpclient.

**Comment by mabdullah353** [comment]
by pre-pending # mine is started working

**Comment by Aleksei-Badyaev** [comment]
May be this plugin prepend channel name by symbol '#' automatically???

**Comment by mabdullah353** [comment]
+1, i think # is useless over here.

**Comment by mummylegs** [comment]
The # is useful -- you use # for channels, no # for private groups, and @ I think for direct messages.  You can therefore send to a public channel using #.

Any ideas on actually troubleshooting this other than adding # to specify channel?

**Comment by warpdesign** [comment]
I am having the same problem: I don't get any messages in slack. I have correctly appened the "#" in front of the channel name.

What is the command line to type to test integration using curl ?

**Comment by sciyoshi** [comment]
Closing this issue - please check if the comment here helps: https://github.com/sciyoshi/redmine-slack/issues/46#issuecomment-166114271
