### ISSUE TITLE
Where is version 0.2?

### ISSUE THREAD

**Issue by Ovsyanka** [sciyoshi/redmine-slack#54]
[here](http://www.redmine.org/plugins/redmine-slack) i see, that actual version is 0.2 and this version supports redmine 3.0.x.
But when install this plugin from master the version is 0.1

And plugin not working for me.

**Comment by XenoPhage** [comment]
I have the same question and problem.  I've pulled via git, but the version is listed as 0.1.  The slack API URL works via curl, but nothing is sent when using the redmine plugin.  Not sure what I'm missing.

**Comment by Ovsyanka** [comment]
I've solved my problem, but the question is still actual.

**Comment by rawzone** [comment]
@XenoPhage I also have this problem - Upgraded Redmine, now no info is send to slack (Worked like a charm before upgrading).

* Slack URL works via curl
* No info is send from Redmine

**Environment:**
  Redmine version                3.2.0.stable
  Ruby version                   2.1.7-p400 (2015-08-18) [amd64-freebsd10]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2

**SCM:**
  Git                            2.6.3
  Filesystem                     

**Redmine plugins:**
  redmine_slack                  0.1

**Comment by sciyoshi** [comment]
Please check the instruction here: https://github.com/sciyoshi/redmine-slack/issues/46#issuecomment-166114271
