### ISSUE TITLE
Plugin Not working redmine3.1.1

### ISSUE THREAD

**Issue by johnp2686** [sciyoshi/redmine-slack#66]
Hi,
I installed configured redmine slack plugin but not able get notifications for each issue update can any one help ,how to configure and how to use this this plugin

**Comment by sciyoshi** [comment]
@johnp2686 - thanks for the report. We've had other people successfully use the plugin with 3.1.1 - could you please provide some more information about what settings you're using or what error messages you're seeing? Thanks!

**Comment by rubendepedro** [comment]
Check this solution out: https://github.com/sciyoshi/redmine-slack/issues/46#issuecomment-166114271
