### ISSUE TITLE
Updates when closing issues with commit messages.

### ISSUE THREAD

**Issue by colinsullivan** [sciyoshi/redmine-slack#7]
Does Redmine have a hook for this one?

Haven't looked into it.

**Comment by MMore** [comment]
+1

**Comment by fzerorubigd** [comment]
Actually I get here to report this one :) so +1

**Comment by megheaiulian** [comment]
+1

**Comment by sciyoshi** [comment]
Many thanks to @megheaiulian for adding support for this feature!
