### ISSUE TITLE
Under which license is this plugin?

### ISSUE THREAD

**Issue by k4200** [sciyoshi/redmine-slack#72]
There's no information about the license of this plugin. I'm writing a similar plugin and might use some of your code if the license permits.

Thanks

**Comment by sciyoshi** [comment]
@k4200 - sorry for the oversight. I should have clarified this earlier, but this plugin is MIT-licensed (and it must be GPL-compatible since it is a plugin for Redmine, which is GPLv2 - see [clarifications here](http://www.gnu.org/licenses/gpl-faq.html#GPLAndPlugins)).

**Comment by k4200** [comment]
Thanks for your clarification.
