### ISSUE TITLE
No slack posts coming up

### ISSUE THREAD

**Issue by pesachzirkind** [sciyoshi/redmine-slack#74]
I've installed redmine_slack and setup the webhook (and also set the channel using '#' at the beginning)
For some reason there is no posts being made to slack.

Here's what I tried:
Creating new bug
Updating bug (updates posted is checked)

What further steps can I take to debug?

Here is current environment setup:

nvironment:
  Redmine version                3.0.4.stable
  Ruby version                   2.1.2-p95 (2014-05-08) [x86_64-linux-gnu]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_slack                  0.1

**Comment by lessmind** [comment]
Try check the log directory under your redmine, should have a lot more information to debug.

**Comment by pesachzirkind** [comment]
Thanks @lessmind I looked into the logs and there is nothing...I tried logging when the listener runs but its not appearing (i changed the config.level to debug) - it seems that the code from the module doesn't even run

**Comment by sciyoshi** [comment]
@pesachzirkind it sounds like the plugin isn't being loaded properly - are you able to post any other debug information? Are other plugins loading correctly?

**Comment by VitalyKrivoshapkin** [comment]
I think, problem in here:
> (and also set the channel using '#' at the beginning)

Your channel in Slack is private?

# - used only for public channels in Slack
@ - used only for direct messages
[no any symbol] - for private channels 

Try to remove '#' symbol from 'Slack channel' plugin settings in Redmine

**Comment by sciyoshi** [comment]
@pesachzirkind I'm closing this issue for now - if you continue having trouble loading the plugin, feel free to reopen with additional details. Thanks!
