### ISSUE TITLE
Redirect Tasks into Multiple Channels

### ISSUE THREAD

**Issue by jshdcca** [sciyoshi/redmine-slack#85]
Hello!

Great plugin to use.
However, how do I redirect specific redmine project alerts to a specific group in Slack?
I tried the custom fields, no luck making it work

Thanks!
Josh

**Comment by VitalyKrivoshapkin** [comment]
Hi, if your specific group is private, then don't use symbol '#'

**Comment by jshdcca** [comment]
Thanks for your response Vitaly. I got it to work.
