### ISSUE TITLE
plugin isn't loaded

### ISSUE THREAD

**Issue by kyuferev** [sciyoshi/redmine-slack#86]
I did the installation steps as required:
1. Cloned the repo into plugins/redmine_slack (so the directory is not redmine-slack)
2. Run bundle install from the plugin directory (so httpclient is installed properly)
3. Restarted apache

Everything is working fine (plugin is present in Administration - Plugins and I can change its settings) except one thing: there are no posts being made into slack channel. I've configured custom text fields called Slack channel and Slack URL for a project, put webhook URL and channel name in it (played with # as well) but no success.

I've checked redmine/log/production.log for errors but found nothing. Here is a part of a log:

```
Started GET "/issues/2781" for XXXXXXXXXX at 2016-04-22 09:57:38 +0300
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"2781"}
  Current user: XXXXXXXX (id=100)
  Rendered issues/_action_menu.html.erb (11.8ms)
  Rendered plugins/redmine_agile/app/views/issues/_issue_story_points.html.erb (0.1ms)
  Rendered attachments/_links.html.erb (5.9ms)
  Rendered issue_relations/_form.html.erb (2.4ms)
  Rendered issues/_relations.html.erb (5.0ms)
  Rendered issues/_action_menu.html.erb (9.4ms)
  Rendered issues/_form_custom_fields.html.erb (3.0ms)
  Rendered issues/_attributes.html.erb (29.9ms)
  Rendered plugins/redmine_agile/app/views/issues/_issue_color_form.html.erb (0.1ms)
  Rendered plugins/redmine_agile/app/views/issues/_issue_story_points_form.html.erb (0.1ms)
  Rendered plugins/redmine_agile/app/views/issues/_agile_data_fields.html.erb (0.7ms)
  Rendered issues/_form.html.erb (61.8ms)
  Rendered attachments/_form.html.erb (3.1ms)
  Rendered issues/_edit.html.erb (86.6ms)
  Rendered plugins/redmine_agile/app/views/agile_boards/_issues_sidebar.html.erb (3.6ms)
  Rendered plugins/redmine_agile/app/views/agile_charts/_agile_charts.html.erb (11.5ms)
  Rendered issues/_sidebar.html.erb (28.8ms)
  Rendered issues/show.html.erb within layouts/base (219.2ms)
Completed 200 OK in 408ms (Views: 258.5ms | ActiveRecord: 35.2ms)
```

As far as I can see there are no records about rendering redmine_slack plugin. 

```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.0
  redmine_slack                  0.1
```

How do I make this plugin work?

**Comment by VitalyKrivoshapkin** [comment]
Did you set channel name in Redmine project -> Settings and at down you can see a "Slack Channel" field

**Comment by kyuferev** [comment]
@VitalyKrivoshapkin Yes I did. Slack channel and Slack URL fields inside the project settings are set up. I want to use this plugin on per-project basis so I've left Slack channel and Slack URL fields in "Administration -> Plugins -> Redminie Slack -> Configure" empty.

**Comment by kyuferev** [comment]
I've tried to restart Redmine. Since Redmine is working with passenger module I've made tmp/restart.txt file with a word "restart" in it. Then I've opened Administration -> Plugins -> Redminie Slack -> Configure page and checked out the log. Here it is:
```
Started GET "/settings/plugin/redmine_slack" for XXXXXXXX at 2016-04-22 11:10:38 +0300
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_slack"}
  Current user: XXXXXXX (id=9)
  Rendered plugins/redmine_slack/app/views/settings/_slack_settings.html.erb (0.1ms)
  Rendered settings/plugin.html.erb within layouts/admin (1.5ms)
  Rendered admin/_menu.html.erb (3.5ms)
  Rendered layouts/base.html.erb (8.9ms)
Completed 200 OK in 21ms (Views: 14.8ms | ActiveRecord: 1.6ms)
```
So now I guess plugin is finally loaded into Redmine. But when I'm trying to update an issue I'm getting this in log:
```
Started PATCH "/issues/2773/edit.js" for XXXXXXXXX at 2016-04-22 11:13:04 +0300
Processing by IssuesController#edit as JS
  Parameters: {XXXXXXXX}
  Current user: XXXXXXX (id=9)
  Rendered issues/_form_custom_fields.html.erb (0.1ms)
  Rendered issues/_attributes.html.erb (12.9ms)
  Rendered plugins/redmine_agile/app/views/issues/_issue_color_form.html.erb (0.1ms)
  Rendered plugins/redmine_agile/app/views/issues/_issue_story_points_form.html.erb (0.1ms)
  Rendered plugins/redmine_agile/app/views/issues/_agile_data_fields.html.erb (0.5ms)
  Rendered issues/_form.html.erb (29.6ms)
  Rendered issues/edit.js.erb (30.7ms)
Completed 200 OK in 69ms (Views: 30.7ms | ActiveRecord: 4.7ms)
Started PATCH "/issues/2773" for 1XXXXXXXXXX at 2016-04-22 11:13:06 +0300
Processing by IssuesController#update as HTML
  Parameters: {XXXXXXXX}
  Current user: XXXXXXX (id=9)
  Rendered mailer/_issue.text.erb (5.7ms)
  Rendered mailer/issue_edit.text.erb within layouts/mailer (8.2ms)
  Rendered mailer/_issue.html.erb (1.7ms)
  Rendered mailer/issue_edit.html.erb within layouts/mailer (3.5ms)
Email delivery error: 550 Relay not permitted

Redirected to https://XXXXXX/issues/2773
Completed 302 Found in 249ms (ActiveRecord: 15.3ms)
Started GET "/issues/2773" for XXXXXXXX at 2016-04-22 11:13:06 +0300
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"2773"}
  Current user: XXXXXXX (id=9)
  Rendered issues/_action_menu.html.erb (5.7ms)
  Rendered plugins/redmine_agile/app/views/issues/_issue_story_points.html.erb (0.1ms)
  Rendered issue_relations/_form.html.erb (2.5ms)
  Rendered issues/_relations.html.erb (3.7ms)
  Rendered issues/_history.html.erb (16.3ms)
  Rendered issues/_action_menu.html.erb (5.2ms)
  Rendered issues/_form_custom_fields.html.erb (0.1ms)
  Rendered issues/_attributes.html.erb (13.6ms)
  Rendered plugins/redmine_agile/app/views/issues/_issue_color_form.html.erb (0.1ms)
  Rendered plugins/redmine_agile/app/views/issues/_issue_story_points_form.html.erb (0.1ms)
  Rendered plugins/redmine_agile/app/views/issues/_agile_data_fields.html.erb (0.8ms)
  Rendered issues/_form.html.erb (37.6ms)
  Rendered attachments/_form.html.erb (3.3ms)
  Rendered issues/_edit.html.erb (60.2ms)
  Rendered plugins/redmine_agile/app/views/agile_boards/_issues_sidebar.html.erb (3.0ms)
  Rendered plugins/redmine_agile/app/views/agile_charts/_agile_charts.html.erb (6.0ms)
  Rendered issues/_sidebar.html.erb (14.5ms)
  Rendered watchers/_watchers.html.erb (4.3ms)
  Rendered issues/show.html.erb within layouts/base (143.2ms)
Completed 200 OK in 363ms (Views: 159.0ms | ActiveRecord: 17.1ms)
```
Still no sign of redmine_slack.

**Comment by VitalyKrivoshapkin** [comment]
" I've left Slack channel and Slack URL fields in "Administration -> Plugins -> Redmine Slack -> Configure" empty."
Don't do that. Try to fill them

**Comment by kyuferev** [comment]
But then it will affect all projects, doesn't it?

**Comment by VitalyKrivoshapkin** [comment]
If you set "Slack Channel" field, then will not

**Comment by kyuferev** [comment]
Still no success. Slack channel and Slack URL fields in project settings and in plugin settings are exactly the same. Maybe there is something wrong with Slack username? Should I change it or leave default "redmine"?

**Comment by VitalyKrivoshapkin** [comment]
try to create a new webhook in Slack, where you must choose a true Slack channel name

**Comment by kyuferev** [comment]
I've tried several times. Right now Slack URL and Slack channel are configured correctly in both plugin and project settings. Channel is public so I'm using # before its name. The only thing I have in mind is server proxy settings. Server is behind proxy and I've set proxy settings by **export http_proxy=...** and **export https_proxy=...** From server console I can ping https://hooks.slack.com so I guess it's working fine, isn't it?

I also don't understand why I'm receiving email delivery error right after issue patch process. Any suggestions?

**Comment by kyuferev** [comment]
From server console I've tried this `curl -X POST -H 'Content-type: application/json' --data '{"text":"test message"}' <Slack URL here>` and I've received this message in Slack. So this isn't a proxy issue.

**Comment by sciyoshi** [comment]
I was thinking this could be the proxy issue, since redmine-slack isn't set
up to honor those settings. Or could it be that the project custom field is
case sensitive? Try changing it to "Slack Channel" with a capital C.

**Comment by kyuferev** [comment]
It is Slack Channel. Is "text" the right format for this custom field? It's set as Visible in Redmine, no other options.

**Comment by mleykin** [comment]
@sciyoshi : So, do you mean that you plugin can't work with proxy server?

**Comment by kyuferev** [comment]
@sciyoshi That was a proxy issue. I've asked IT to give direct internet access for this server and everything works fine now.
