### ISSUE TITLE
NameError: undefined local variable or method `logger'

### ISSUE THREAD

**Issue by eloylm** [sciyoshi/redmine-slack#97]
Completed 500 Internal Server Error in 452ms (ActiveRecord: 164.5ms)

`NameError (undefined local variable or method`logger' for #SlackListener:0x00000008ff2cf8):
  plugins/redmine_slack/lib/redmine_slack/listener.rb:158:in `rescue in speak'
  plugins/redmine_slack/lib/redmine_slack/listener.rb:152:in`speak'
  plugins/redmine_slack/lib/redmine_slack/listener.rb:56:in `controller_issues_edit_after_save'
  lib/redmine/hook.rb:61:in`block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in`block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in`call_hook'
  lib/redmine/hook.rb:91:in `call_hook'
  app/controllers/issues_controller.rb:489:in`block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:476:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:180:in`update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`

**Solution -> In  plugins/redmine_slack/lib/redmine_slack/listener.rb, change:
logger.warn
for
Rails.logger.warn**

**Comment by sciyoshi** [comment]
Thanks @eloylm for reporting this issue. Do you know which versions this affects?

**Comment by sciyoshi** [comment]
I've pushed a fix that should resolve this. Please let me know if this helps!
